### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by plmercereau**
Improve logging
- use winston instead of pino (more flexible)
- log uncaught errors
- common fields: `level`, `message`
- common HTTP fields: `method`, `responseTime` (ms), `status`, `url`
- hide details on 2xx and 4xx codes
- keep a certain level or details e.g headers on 401, 403 and 5xx

Example of a sequence:
- startup
- signup with email verification
- confirm email
- sign in
- sign-in attempt with a wrong password

Output with the default `info` log level:

```json
{"level":"info","message":"Log level: info"}
{"level":"info","message":"Waiting for Hasura to be ready..."}
{"level":"info","message":"Hasura is ready"}
{"level":"info","message":"Applying SQL migrations..."}
{"level":"info","message":"SQL migrations applied"}
{"level":"info","message":"Applying metadata..."}
{"level":"info","message":"Metadata applied"}
{"level":"info","message":"Running on port 4000"}
{"latencyInNs":352000000,"level":"info","message":"POST /signup/email-password 200 352ms","method":"POST","statusCode":200,"url":"/signup/email-password"}
{"latencyInNs":81000000,"level":"info","message":"GET /verify?***** 302 81ms","method":"GET","statusCode":302,"url":"/verify?*****"}
{"latencyInNs":190000000,"level":"info","message":"POST /signin/email-password 200 190ms","method":"POST","statusCode":200,"url":"/signin/email-password"}
{"latencyInNs":122000000,"level":"warn","message":"POST /signin/email-password 401 122ms","method":"POST","statusCode":401,"url":"/signin/email-password"}
```

Output with `debug` log level:
```json
{"level":"info","message":"Log level: debug"}
{"level":"info","message":"Waiting for Hasura to be ready..."}
{"level":"info","message":"Hasura is ready"}
{"level":"info","message":"Applying SQL migrations..."}
{"level":"info","message":"SQL migrations applied"}
{"level":"info","message":"Applying metadata..."}
{"level":"debug","message":"Exporting metadata..."}
{"level":"debug","message":"Applying metadata patch..."}
{"level":"info","message":"Metadata applied"}
{"level":"info","message":"Running on port 4000"}
{"level":"debug","message":"Using email template: /Users/pilou/dev/nhost/hasura-auth/email-templates/en/email-verify/subject.txt"}
{"level":"debug","message":"Using email template: /Users/pilou/dev/nhost/hasura-auth/email-templates/en/email-verify/body.html"}
{"level":"debug","message":"Using email template: /Users/pilou/dev/nhost/hasura-auth/email-templates/en/email-verify/body.txt"}
{"headers":{"accept":"*/*","accept-encoding":"gzip, deflate, br","cache-control":"no-cache","connection":"keep-alive","content-length":"110","content-type":"application/json","host":"localhost:4000","postman-token":"44ef8ba8-beed-4c9a-818f-bab70a093066","user-agent":"PostmanRuntime/7.29.2"},"latencyInNs":303000000,"level":"info","message":"POST /signup/email-password 200 303ms","method":"POST","statusCode":200,"url":"/signup/email-password"}
{"headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","accept-encoding":"gzip, deflate, br","accept-language":"en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7","connection":"keep-alive","cookie":"_ga=GA1.1.408920539.1663872509; intercom-id-a772tk9n=751ed9b2-bdba-4c29-b1f4-d1ad9dd217b8; ajs_anonymous_id=a86529da-447d-4f88-8226-c0ad9c2385eb; nhostRefreshToken=5731b7ce-ca15-4edd-bcb1-a10a3aa7aa80; nhostRefreshTokenExpiresAt=2022-10-07T10:01:59.762Z","dnt":"1","host":"localhost:4000","sec-ch-ua":"\"Chromium\";v=\"106\", \"Google Chrome\";v=\"106\", \"Not;A=Brand\";v=\"99\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"macOS\"","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"cross-site","sec-fetch-user":"?1","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"},"latencyInNs":79000000,"level":"info","message":"GET /verify?&ticket=verifyEmail:fbe67db6-6be1-4e91-9104-560af8bc99ab&type=emailVerify&redirectTo=http%3A%2F%2Flocalhost%3A3000 302 79ms","method":"GET","statusCode":302,"url":"/verify?&ticket=verifyEmail:fbe67db6-6be1-4e91-9104-560af8bc99ab&type=emailVerify&redirectTo=http%3A%2F%2Flocalhost%3A3000"}
{"level":"debug","message":"Sign in with email: pilou@pilou.com"}
{"headers":{"accept":"*/*","accept-encoding":"gzip, deflate, br","cache-control":"no-cache","connection":"keep-alive","content-length":"63","content-type":"application/json","host":"localhost:4000","postman-token":"07740c7f-1ecd-480c-b4d6-836e059f3d7b","user-agent":"PostmanRuntime/7.29.2"},"latencyInNs":157000000,"level":"info","message":"POST /signin/email-password 200 157ms","method":"POST","statusCode":200,"url":"/signin/email-password"}
{"level":"debug","message":"Sign in with email: pilou@pilou.com"}
{"headers":{"accept":"*/*","accept-encoding":"gzip, deflate, br","cache-control":"no-cache","connection":"keep-alive","content-length":"66","content-type":"application/json","host":"localhost:4000","postman-token":"4da204dc-a27d-462f-a128-68dd82467242","user-agent":"PostmanRuntime/7.29.2"},"latencyInNs":124000000,"level":"warn","message":"POST /signin/email-password 401 124ms","method":"POST","statusCode":401,"url":"/signin/email-password"}
```

### CODE REVIEW

**Comment by elitan** [comment]
Wow, this is so much cleaner and nicer!

### Overlapping Info

There is overlapping information in `message` and the rest of the JSON object for requests. 

Like this:

```
{"level":"info","message":"POST /signup/email-password 200 377ms","method":"POST","responseTime":377,"status":200,"url":"/signup/email-password"}
```

Is `message` necessary?

### Hasura Storage

Do we plan to use the same logging format in Hasura Storage?

**Comment by plmercereau** [comment]
> ### Overlapping Info
> There is overlapping information in `message` and the rest of the JSON object for requests.
> 
> Is `message` necessary?
No, all the information is present in other fields on http requests. However, for non-http requests (for instance startup logs) there is a message. I would keep the message field for every log entry so it can be used on filtering/labelling log entries

**Comment by nunopato** [comment]
My thoughts:

- we should change storage to use JSON logging
- we should converge to the same fields:
- - time (missing here in hasura auth, storage is using a timestamp in UTC)
- -  level (info, debug, etc) - already in both places
- - message
- - status (storage is using `status_code`)
- - URL (already in both places)
- - method (already in both places)
- - latency_time (storage has this but not sure if it is useful for the user with `info` level)

**Comment by plmercereau** [comment]
> * * time (missing here in hasura auth, storage is using a timestamp in UTC) - should be added here

we already have the timestamp of when logs are written, I can add a `time` field if you like

> * * latency_time (storage has this but not sure if it is useful for the user with `info` level)
I set Winston's default `responseTime` in milliseconds. We won't be able to get the details in microseconds. I can add three zeros and rename the field if you like

I have 0 opinion on the matter, let me know what you want and I'll adapt the code.

**Comment by elitan** [comment]
milliseconds should be enough. We might have to update Storage to also use microseconds :o

**Comment by plmercereau** [comment]
update following our discussion with David and Nuno

**Pull request merged**
